version: '2.1'

networks:
  mysql:
    external:
      name: mysql

  proxy:
    external:
      name: proxy

services:
  main:
    image: httpd:2.4-alpine
    volumes:
      - "${DOCKER_COMPOSE_TEMPLATE_PATH}/docker-compose.php-fpm.httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
      - "$DUMB_INIT_BIN:/usr/local/bin/dumb-init:ro"
      - "$WEB_ROOT:/app"
    networks:
      - proxy
      - default
    entrypoint: ["/usr/local/bin/dumb-init","--rewrite","28:0", "--"]
    command: ["httpd-foreground"]
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${HOST}
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=proxy

  php:
    image: webvariants/php:${VERSION}-fpm-alpine
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "$WEB_ROOT:/app"
    networks:
      - default
      - mysql
      - proxy # to access mongo-xh
    working_dir: "/app"
    user: $USER_UID:$USER_GID
    environment:
      PHP_IMAGE_VERSION: "2"
      WEB_ROOT: "/app"
      APP_DATA: "/app/data"
      WWW_DATA_UID: "$USER_UID"
      WWW_DATA_GID: "$USER_GID"
      WWW_USER: "$USER_NAME"
      WWW_GROUP: "$USER_GROUP"
      PHP_TYPO3_INI: "1"
      PHP_OPCACHE_INI: "1"
      PHP_OPCACHE_INI_FAST_SHUTDOWN: "1"
      PHP_ZEND_EXTENSIONS: "xdebug.so"
      PHPINI_XDEBUG__REMOTE_ENABLE: "1"
      PHPINI_XDEBUG__REMOTE_CONNECT_BACK: "1"
      PHPINI_XDEBUG__REMOTE_PORT: "9000"
      PHPINI_XDEBUG__REMOTE_HANDLER: "dbgp"
      PHPINI_XDEBUG__REMOTE_MODE: "req"
      PHPINI_XDEBUG__REMOTE_AUTOSTART: "true"
      PHPINI_AUTO_START: "0"
      PHPINI_XDEBUG__PROFILER_OUTPUT_DIR: "/app/data"
      PHPINI_XDEBUG__PROFILER_ENABLE: 0
      PHPINI_XDEBUG__PROFILER_ENABLE_TRIGGER: 1

      PHPINI_AUTO_PREPEND_FILE: "/xhgui/header.php"
      XHGUI_PROBABILITY: 100
      XHGUI_FULL_PROFILING: 1
