version: "2.3"

networks:
  mysql:
    name: mysql
  proxy:
    name: proxy
  traefik:
    name: traefik

services:
  mysql:
    image: mysql:5.7
    command:
      - "mysqld"
      - "--sql_mode="
      - "--innodb_buffer_pool_size=1G"
      - "--innodb_log_file_size=256M"
      - "--innodb_flush_log_at_trx_commit=1"
      - "--innodb_flush_method=O_DIRECT"
    # https://www.percona.com/blog/2016/10/12/mysql-5-7-performance-tuning-immediately-after-installation/
    environment: ["MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?please set mysql root password}"]
    volumes: ["./data/mysql/lib:/var/lib/mysql"]
    networks: ["mysql"]
    restart: unless-stopped
    labels: ["traefik.enable=false"]
    mem_limit: 500M
    memswap_limit: 600M
    ports: ["127.0.0.1:3306:3306", "::1:3306:3306"]

  # traefik:
  #   image: traefik
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./config/traefik.toml:/traefik.toml:ro"
  #     - "./certs/:/certs/:ro" # run ./hosts_certs to create certificates for /etc/hosts first!
  #     - type: tmpfs
  #       target: /tmp
  #   ports: ["127.0.0.1:8080:8080", "127.0.0.1:80:80", "127.0.0.1:443:443", "::1:8080:8080", "::1:80:80", "::1:443:443"]
  #   networks: ["proxy", "traefik"]
  #   restart: unless-stopped
  #   mem_limit: 200M
  #   memswap_limit: 250M

  nginx:
    image: webvariants/nginx-acme-and-more
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./certs/:/etc/nginx/certs/:ro
      - ./dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - ./log:/var/log/nginx
      - ./html:/html:ro
    tmpfs:
      - /tmp
    ports: ["127.0.0.1:8080:8080", "127.0.0.1:80:80", "127.0.0.1:443:443", "::1:8080:8080", "::1:80:80", "::1:443:443"]
    networks: ["proxy", "traefik"]
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    mem_limit: 512M
    memswap_limit: 513M

  nginx-dconf:
    build:
      context: .
      dockerfile: Dockerfile.nginx-dconf
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./conf.d/:/etc/nginx/conf.d/
      - ./nginx-dconf:/etc/nginx/nginx-dconf:ro
      - ./html:/html
    working_dir: /etc/nginx/
    user: 101:${DOCKER_GID:?please run ./init first}
    restart: unless-stopped
    mem_limit: 200M
    memswap_limit: 250M

  mail:
    image: djfarrelly/maildev
    labels: ["traefik.port=80", "traefik.enable=true", "traefik.docker.network=proxy"]
    restart: unless-stopped
    mem_limit: 50M
    memswap_limit: 100M
    networks: ["proxy"]

  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/portainer/data:/data"
    labels: ["traefik.port=9000", "traefik.enable=true", "traefik.docker.network=proxy"]
    restart: unless-stopped
    mem_limit: 100M
    memswap_limit: 200M
    networks: ["proxy"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
#     - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:?please set mysql root password}
    restart: unless-stopped
    volumes:
      - ./data/phpmyadmin/sessions:/sessions
    labels: ["traefik.port=80", "traefik.enable=true", "traefik.docker.network=proxy"]
    networks: ["mysql", "proxy"]

  mongo-xh:
    image: percona/percona-server-mongodb:3.6
    restart: unless-stopped
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=inMemory
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./xhgui.js:/docker-entrypoint-initdb.d/xhgui.js:ro
      - ./data/mongodb:/data/db # 1001
    networks: ["proxy"]
