version: "2.3"

services:

  nginx:
    volumes:
      - ./acme.sh/:/etc/ssl/acme.sh/

  nginx-dconf:
    volumes:
      - ./acme.sh/:/etc/ssl/acme.sh/
    environment:
      - DCONF_ACME_SH_DIR=/etc/ssl/acme.sh
      - SIGNAL_CONTAINER=${SIGNAL_CONTAINER:-proxy_nginx_1}

  cron-acme:
    image: webvariants/nginx-acme-and-more
    build: .
    restart: always
    depends_on:
      - nginx
    command: cron-acme
    volumes:
      - ./acme.sh/:/etc/ssl/acme.sh/
      - ./html/:/usr/share/nginx/html/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ACME_CRON=${ACME_CRON-27 10 * * 1-4}
      - SIGNAL_CONTAINER=${SIGNAL_CONTAINER:-proxy_nginx_1}
    user: nginx:${DOCKER_GID-999}
    read_only: true
    tmpfs:
      - /tmp
    mem_limit: 128m
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 512k
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_CRON_ACME:-1}

  cron-rotate-log:
    image: webvariants/nginx-acme-and-more
    restart: always
    depends_on:
      - nginx
    command: cron-rotate-log
    volumes:
      - ./log/:/var/log/nginx
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SIGNAL_CONTAINER=${SIGNAL_CONTAINER:-proxy_nginx_1}
    user: nginx:${DOCKER_GID-999}
    read_only: true
    mem_limit: 128m
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 512k
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_CRON_ROTATE_LOG:-1}

  portainer:
    labels:
      - traefik.frontend.rule=Host:portainer.${BASE_DOMAIN:?}
      - dconf.cert.acme.sh=${ACME_SH_CERT_PORTAINER}

  mail:
    labels:
      - traefik.frontend.rule=Host:mail.${BASE_DOMAIN:?}
      - dconf.auth.username=${MAIL_AUTH_USERNAME:?}
      - dconf.auth.password=${MAIL_AUTH_PASSWORD:?}
      - dconf.cert.acme.sh=${ACME_SH_CERT_MAIL}


  phpmyadmin:
    labels:
      - traefik.frontend.rule=Host:phpmyadmin.${BASE_DOMAIN:?}
      - dconf.auth.username=${PHPMYADMIN_AUTH_USERNAME:?}
      - dconf.auth.password=${PHPMYADMIN_AUTH_PASSWORD:?}
      - dconf.cert.acme.sh=${ACME_SH_CERT_PHPMYADMIN}

  xhgui:
    labels:
      - traefik.frontend.rule=Host:xhgui.${BASE_DOMAIN:?}
      - dconf.auth.username=${XHGUI_AUTH_USERNAME:?}
      - dconf.auth.password=${XHGUI_AUTH_PASSWORD:?}
      - dconf.cert.acme.sh=${ACME_SH_CERT_XHGUI}
